lib/generators/yorchauth/templates/config/routes.rb
# User Authentication routes.

resources :users, only: %i[create]
get '/signup', to: 'users#new'
get '/users/:token_id', to: 'users#show', as: 'user'
get '/users/edit/:token_id', to: 'users#edit', as: 'edit_user'
patch '/users/edit/:token_id', to: 'users#update', as: 'update_user'
delete '/users/destroy/:token_id', to: 'users#destroy', as: 'destroy_user'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#logout'
get '/email/confirmation/:token_id', to: 'users#confirm_account', as: 'confirm_user_account'

lib/generators/yorchauth/templates/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token :token_id, length: 50

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }, on: :create
  validates :password_confirmation, presence: true, length: { minimum: 8 }, on: :create

  def confirmed?
    active
  end
end

lib/generators/yorchauth/templates/app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
  before_action :authenticate_user
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  private

  def authenticate_user
    redirect_to login_path, notice: 'Please, sign in to use this application' unless logged_in?
  end

  def deny_access
    return if session[:user_id].nil?

    redirect_to root_path, notice: 'You cannot access. Please sign out.'
  end
end

lib/generators/yorchauth/templates/app/controllers/sessions_controller.rb
class SessionsController < AuthenticateController
  skip_before_action :authenticate_user
  before_action :deny_access, only: %i[new create]
  before_action :set_user, only: %i[create]

  def new; end

  def create
    if @user&.authenticate(params[:session][:password])
      if @user.confirmed?
        session[:user_id] = @user.id
        redirect_to root_path
      else
        redirect_to login_path, notice: 'Your account has not been activated.'
      end
    else
      flash[:notice] = 'Incorrect email or password.'
      redirect_to login_path, status: :unprocessable_entity
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def set_user
    @user = User.find_by(email: params[:session][:email])
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

lib/generators/yorchauth/templates/app/controllers/users_controller.rb
class UsersController < AuthenticateController
  skip_before_action :authenticate_user, only: %i[new create confirm_account]
  before_action :deny_access, only: %i[new create]
  before_action :set_user, only: %i[edit update show destroy confirm_account]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def edit; end

  def show; end

  def create
    @user = User.new user_params

    if @user.save
      UserMailer.with(user: @user).send_email_confirmation.deliver_later
      flash[:notice] = 'An email has been sent to your email account. Click on the link to validate your account.'
      redirect_to login_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.authenticate(params[:user][:old_password])
      if @user.update user_params
        flash[:notice] = 'Account updated successfully'
        redirect_to user_path(@user.token_id)
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:notice] = 'Your current password is invalid'
      redirect_to edit_user_path(@user.token_id), status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy

    flash[:notice] = 'Your account has been deleted successfully'
    redirect_to login_path
  end

  def confirm_account
    if @user.present?
      if @user.confirmed?
        flash[:notice] = 'You have already confirmed your email account'
      else
        @user.update!(active: true)
        flash[:notice] = 'Your account has been successfully confirmed'
      end
    else
      flash[:notice] = 'You can not confirm this account because it is not linked to any user.'
    end
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by(token_id: params[:token_id])
    return @user if @user.present?

    flash[:notice] = 'There is not user with this token'
    redirect_to root_path
  end

  def authorize_user
    return if current_user.eql? @user

    flash[:notice] = "You are not authorized to perform this action"
    redirect_to root_path
  end
end

lib/generators/yorchauth/templates/app/views/layouts/application.html.erb
<%= render 'shared/navbar' %>
<p><%= notice if notice %></p>

lib/generators/yorchauth/templates/app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <% if current_user %>
      <li>
        <%= link_to root_path, id: 'root_path' do %>
          My app
        <% end %>
      </li>

      <li>
        <%= button_to logout_path, method: :delete, id: 'close_session' do %>
          Log out
        <% end %>
      </li>

      <li>
        <%= button_to user_path(current_user.token_id), method: :get, id: 'show_user' do %>
          Profile
        <% end %>
      </li>

      <li>
        <%= button_to edit_user_path(current_user.token_id), method: :get, id: 'edit_user' do %>
          Edit Account
        <% end %>
      </li>

    <% else %>
      <li>
        <%= link_to login_path, id: 'login_navbar_link' do %>
          Login
        <% end %>
      </li>

      <li>
        <%= link_to signup_path, id: 'signup_navbar_link' do %>
          Sign Up
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

lib/generators/yorchauth/templates/app/views/users/_form.html.erb
<%= form_with(model: user, id: 'user_form', url: url) do |form| %>
  <% if user.errors.any? %>
    <ul>
      <% user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :email, 'Email:' %>
    <%= form.email_field :email %>
  </div>

  <div>
    <span>Your password should have at least 8 characters</span> <br>
    <%= form.label :password, 'New password:' %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, 'Password Confirmation:' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <% if authorize %>
    <div>
      <%= form.label :old_password, 'Please type your old password to change your profile:' %>
      <%= form.password_field :old_password  %>
    </div>
  <% end %>

  <div>
    <%= form.submit text_btn %>
  </div>
<% end %>

lib/generators/yorchauth/templates/app/views/users/edit.html.erb
<%= render 'form', { user: @user, text_btn: 'Update account', url: update_user_path(@user.token_id), authorize: true } %>

<%= link_to :back, id: 'cancel_btn' do %>
  Cancel
<% end %>
<div>
  <p>Danger zone:</p>
  <%= button_to destroy_user_path, method: :delete, id: 'cancel_account', form: { data: { turbo_confirm: '¿Estás seguro de inhabilitar este registro?' } } do %>
    Cancel Account
  <% end %>
</div>

lib/generators/yorchauth/templates/app/views/users/new.html.erb
<%= render 'form', { user: @user, text_btn: 'Sign Up', url: users_path, authorize: false } %>

lib/generators/yorchauth/templates/app/views/users/show.html.erb
<h3>Account Details</h3>
<div>
  <p><%= @user.email %></p>
</div>